name: Deploy Website

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          sudo apt install -y imagemagick
      - name: Build website
        run: |
          make publish
      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: publish-build
          path: build
  upload:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - name: Get Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: publish-build
          path: build
      - name: Display structure of downloaded files
        run: ls -R build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy build --project-name=declan-gaylo-www
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
