name: Pull Request Checks

on:
  pull_request: 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [ "${{ github.base_ref }}", "${{ github.head_ref }}"]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          sudo apt install -y imagemagick
      - name: Build website
        run: |
          make publish
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: publish-${{ matrix.branch }}
          path: build

  compare:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get ref build artifacts
        uses: actions/download-artifact@v4
        with:
          name: publish-${{ github.base_ref }}
          path: build-base
      - name: Get head build artifacts
        uses: actions/download-artifact@v4
        with:
          name: publish-${{ github.head_ref }}
          path: build-head
      - name: Generate diff
        run: |
          diff -r build-base build-head > diff.txt || [ $? -eq 1 ]
      - name: Comment diff in PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: diff.txt
    